version: '3'

services:
  db:
    image: postgres:15
    container_name: db
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - .env
  app:
    build:
      context: .
    container_name: app
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    command: ["/app/docker/app.sh"]
    ports:
      - "8000:8000"
    